spring:
  profiles.active: dev
  application.name: Rookie-Blog
  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

project:
  github:
    repo: https://github.com/patton174/Rookie-Blog/tree/backend
