################## 开发环境配置 ##################
server:
  port: 12345
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:my_blog}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:LIxu2002}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
      database: 0
      timeout: 2s
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-account@example.com}
    password: ${MAIL_PASSWORD:your-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: 
  web:
    resources:
      add-mappings: true

# 开发环境可以显示更详细的日志
logging:
  level:
    com.lx.blog: INFO

mybatis-plus:
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
    # 开启 MyBatis Plus 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# sa-token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: rookie-blog-session-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

app:
  host: http://localhost:5173

springdoc:
  swagger-ui:
    path: /doc
